config/routes.rb
Rails.application.routes.draw do

    # This line mounts Spree's routes at the root of your application.
    # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
    # If you would like to change where this engine is mounted, simply change the :at option to something different.
    #
    # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => 'users/registrations'}

    resources :temperaments
    resources :wheels
    resources :experiences
    resources :users, :except =>[:destroy]
    resources :tasks
    resources :goals
    resources :humors, :except =>[:destroy,:edit]
    resources :wheel_of_lives, :except =>[:destroy,:edit]
    resources :temperaments, :except =>[:destroy,:edit]
    resources :notifications

    root :to => "users#index"

    

    namespace :api do

        scope :users do
          post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
          post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
          delete '/sign_out_mobile',to:'/api/sessions#destroy'
          post '/reset_password',to:'/api/sessions#reset_password'
          post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
        end

        scope :goals do
            patch '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
        end

        get '/humors',to:'/api/humors#index', defaults: { format: 'json' }

        post '/create_humor',to:'/api/humors#create_humor', defaults: { format: 'json' }

        get '/goals',to:'/api/goals#index', defaults: { format: 'json' }

        post '/create_goal_image',to:'/api/goals#create_multipart_goal', defaults: { format: 'json' }

        get '/goals/:id',to:'/api/goals#show_goal', defaults: { format: 'json' }

        delete '/delete_goal/:id',to:'/api/goals#delete_goal', defaults: { format: 'json' }

        put '/finalize_goal/:id',to:'/api/goals#finalize_goal', defaults: { format: 'json' }

        get '/wheels',to:'/api/wheels#index', defaults: { format: 'json' }

        post '/new_wheel_of_life',to:'/api/wheels#create_wheel', defaults: { format: 'json' }

        get '/wheel_of_life',to:'/api/wheels#show_wheel', defaults: { format: 'json' }

        get '/temperaments',to:'/api/temperaments#index', defaults: { format: 'json' }

        post '/new_temperament',to:'/api/temperaments#create', defaults: { format: 'json' }

        get '/tasks',to:'/api/tasks#index', defaults: { format: 'json' }

        get '/tasks/:id',to:'/api/tasks#show_task', defaults: { format: 'json' }

        delete '/delete_task/:id',to:'/api/tasks#delete_task', defaults: { format: 'json' }

        put '/finalize_task/:id',to:'/api/tasks#finalize_task', defaults: { format: 'json' }

        get '/get_tasks/:goal_id',to:'/api/tasks#get_tasks', defaults: { format: 'json' }

        post '/create_task',to:'/api/tasks#create_task', defaults: { format: 'json' }

        get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

        post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' }

        get '/experiences',to:'/api/experiences#index', defaults: { format: 'json' }

        put '/update_mobile_multipart',to:'/api/registrations#update_multipart', defaults: { format: 'json' }

    end

end

app/models/temperament.rb
class Temperament < ActiveRecord::Base
	belongs_to :user
end

app/controllers/api/temperaments_controller.rb
class Api::TemperamentsController < Api::BaseController

	respond_to :json

	def index
		@temperaments = Temperament.where(user: current_user)
		render 'temperaments/index.json.jbuilder'
		return @temperaments
	end

	def create
		@temperament = Temperament.new(temperament_params)
		@temperament.user = current_user
		@temperament.save
		render 'temperaments/show.json.jbuilder'
	end

	def temperament_params
		params.require(:temperament).permit(:id, :will_result, :wish_result, :fury_result, :inhibition_result, :sensibility_result, :coping_result, :user_id)
	end

end

app/controllers/temperaments_controller.rb
class TemperamentsController < ApplicationController
  before_action :set_temperament, only: [:show, :edit, :update, :destroy]

  # GET /temperaments
  # GET /temperaments.json
  def index
    @temperaments = Temperament.all
  end

  # GET /temperaments/1
  # GET /temperaments/1.json
  def show
  end

  # GET /temperaments/new
  def new
    @temperament = Temperament.new
  end

  # GET /temperaments/1/edit
  def edit
  end

  # POST /temperaments
  # POST /temperaments.json
  def create
    @temperament = Temperament.new(temperament_params)

    respond_to do |format|
      if @temperament.save
        format.html { redirect_to @temperament, notice: 'Temperament was successfully created.' }
        format.json { render :show, status: :created, location: @temperament }
      else
        format.html { render :new }
        format.json { render json: @temperament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperaments/1
  # PATCH/PUT /temperaments/1.json
  def update
    respond_to do |format|
      if @temperament.update(temperament_params)
        format.html { redirect_to @temperament, notice: 'Temperament was successfully updated.' }
        format.json { render :show, status: :ok, location: @temperament }
      else
        format.html { render :edit }
        format.json { render json: @temperament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperaments/1
  # DELETE /temperaments/1.json
  def destroy
    @temperament.destroy
    respond_to do |format|
      format.html { redirect_to temperaments_url, notice: 'Temperament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperament
      @temperament = Temperament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temperament_params
      params.require(:temperament).permit(:will_result, :wish_result, :fury_result, :inhibition_result, :sensibility_result, :coping_result, :user_id)
    end
end

app/helpers/temperaments_helper.rb
module TemperamentsHelper
end

app/views/temperaments/_form.html.erb
<%= form_for(@temperament) do |f| %>
  <% if @temperament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temperament.errors.count, "error") %> prohibited this temperament from being saved:</h2>

      <ul>
      <% @temperament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :will_result %><br>
    <%= f.number_field :will_result %>
  </div>
  <div class="field">
    <%= f.label :wish_result %><br>
    <%= f.number_field :wish_result %>
  </div>
  <div class="field">
    <%= f.label :fury_result %><br>
    <%= f.number_field :fury_result %>
  </div>
  <div class="field">
    <%= f.label :inhibition_result %><br>
    <%= f.number_field :inhibition_result %>
  </div>
  <div class="field">
    <%= f.label :sensibility_result %><br>
    <%= f.number_field :sensibility_result %>
  </div>
  <div class="field">
    <%= f.label :coping_result %><br>
    <%= f.number_field :coping_result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temperaments/edit.html.erb
<h1>Editing Temperament</h1>

<%= render 'form' %>

<%= link_to 'Show', @temperament %> |
<%= link_to 'Back', temperaments_path %>

app/views/temperaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temperaments</h1>

<table>
  <thead>
    <tr>
      <th>Will result</th>
      <th>Wish result</th>
      <th>Fury result</th>
      <th>Inhibition result</th>
      <th>Sensibility result</th>
      <th>Coping result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temperaments.each do |temperament| %>
      <tr>
        <td><%= temperament.will_result %></td>
        <td><%= temperament.wish_result %></td>
        <td><%= temperament.fury_result %></td>
        <td><%= temperament.inhibition_result %></td>
        <td><%= temperament.sensibility_result %></td>
        <td><%= temperament.coping_result %></td>
        <td><%= link_to 'Show', temperament %></td>
        <td><%= link_to 'Edit', edit_temperament_path(temperament) %></td>
        <td><%= link_to 'Destroy', temperament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperament', new_temperament_path %>

app/views/temperaments/new.html.erb
<h1>New Temperament</h1>

<%= render 'form' %>

<%= link_to 'Back', temperaments_path %>

app/views/temperaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Will result:</strong>
  <%= @temperament.will_result %>
</p>

<p>
  <strong>Wish result:</strong>
  <%= @temperament.wish_result %>
</p>

<p>
  <strong>Fury result:</strong>
  <%= @temperament.fury_result %>
</p>

<p>
  <strong>Inhibition result:</strong>
  <%= @temperament.inhibition_result %>
</p>

<p>
  <strong>Sensibility result:</strong>
  <%= @temperament.sensibility_result %>
</p>

<p>
  <strong>Coping result:</strong>
  <%= @temperament.coping_result %>
</p>

<%= link_to 'Edit', edit_temperament_path(@temperament) %> |
<%= link_to 'Back', temperaments_path %>