config/routes.rb
Rails.application.routes.draw do

    # This line mounts Spree's routes at the root of your application.
    # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
    # If you would like to change where this engine is mounted, simply change the :at option to something different.
    #
    # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => 'users/registrations'}

    resources :temperaments
    resources :wheels
    resources :experiences
    resources :users, :except =>[:destroy]
    resources :tasks
    resources :goals
    resources :humors, :except =>[:destroy,:edit]
    resources :wheel_of_lives, :except =>[:destroy,:edit]
    resources :temperaments, :except =>[:destroy,:edit]
    resources :notifications

    root :to => "users#index"

    

    namespace :api do

        scope :users do
          post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
          post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
          delete '/sign_out_mobile',to:'/api/sessions#destroy'
          post '/reset_password',to:'/api/sessions#reset_password'
          post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
        end

        scope :goals do
            patch '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
        end

        get '/humors',to:'/api/humors#index', defaults: { format: 'json' }

        post '/create_humor',to:'/api/humors#create_humor', defaults: { format: 'json' }

        get '/goals',to:'/api/goals#index', defaults: { format: 'json' }

        post '/create_goal_image',to:'/api/goals#create_multipart_goal', defaults: { format: 'json' }

        get '/goals/:id',to:'/api/goals#show_goal', defaults: { format: 'json' }

        delete '/delete_goal/:id',to:'/api/goals#delete_goal', defaults: { format: 'json' }

        put '/finalize_goal/:id',to:'/api/goals#finalize_goal', defaults: { format: 'json' }

        get '/wheels',to:'/api/wheels#index', defaults: { format: 'json' }

        post '/new_wheel_of_life',to:'/api/wheels#create_wheel', defaults: { format: 'json' }

        get '/wheel_of_life',to:'/api/wheels#show_wheel', defaults: { format: 'json' }

        get '/temperaments',to:'/api/temperaments#index', defaults: { format: 'json' }

        post '/new_temperament',to:'/api/temperaments#create', defaults: { format: 'json' }

        get '/tasks',to:'/api/tasks#index', defaults: { format: 'json' }

        get '/tasks/:id',to:'/api/tasks#show_task', defaults: { format: 'json' }

        delete '/delete_task/:id',to:'/api/tasks#delete_task', defaults: { format: 'json' }

        put '/finalize_task/:id',to:'/api/tasks#finalize_task', defaults: { format: 'json' }

        get '/get_tasks/:goal_id',to:'/api/tasks#get_tasks', defaults: { format: 'json' }

        post '/create_task',to:'/api/tasks#create_task', defaults: { format: 'json' }

        get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

        post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' }

        get '/experiences',to:'/api/experiences#index', defaults: { format: 'json' }

        put '/update_mobile_multipart',to:'/api/registrations#update_multipart', defaults: { format: 'json' }

    end

end

app/models/wheel.rb
class Wheel < ActiveRecord::Base
	belongs_to :user
end

app/controllers/api/wheels_controller.rb
class Api::WheelsController < Api::BaseController

	def index
		@wheels = Wheel.where(user: current_user)
		render 'wheels/index.json.jbuilder'
	end

	def create_wheel
	    @wheel = Wheel.new(wheel_params)
	    @wheel.user = current_user
		@wheel.save

		render 'wheels/show.json.jbuilder' 
		return @wheel
	end

	def show_wheel
		@wheel = Wheel.find(params[:id])
		render 'wheels/show.json.jbuilder' 
	end

	def wheel_params
		params.require(:wheel).permit(:emotional_balance, :health_and_disposition, :intellectual_development, :career_and_business, :finances, :social_contribution, :recreation, :satisfaction_and_fullfillment, :spirituality, :family, :relationship_with_love, :social_life, :user_ids)
	end


end 

app/controllers/wheels_controller.rb
class WheelsController < ApplicationController
  before_action :set_wheel, only: [:show, :edit, :update, :destroy]

  # GET /wheels
  # GET /wheels.json
  def index
    @wheels = Wheel.all
  end

  # GET /wheels/1
  # GET /wheels/1.json
  def show
  end

  # GET /wheels/new
  def new
    @wheel = Wheel.new
  end

  # GET /wheels/1/edit
  def edit
  end

  # POST /wheels
  # POST /wheels.json
  def create
    @wheel = Wheel.new(wheel_params)

    respond_to do |format|
      if @wheel.save
        format.html { redirect_to @wheel, notice: 'Wheel was successfully created.' }
        format.json { render :show, status: :created, location: @wheel }
      else
        format.html { render :new }
        format.json { render json: @wheel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wheels/1
  # PATCH/PUT /wheels/1.json
  def update
    respond_to do |format|
      if @wheel.update(wheel_params)
        format.html { redirect_to @wheel, notice: 'Wheel was successfully updated.' }
        format.json { render :show, status: :ok, location: @wheel }
      else
        format.html { render :edit }
        format.json { render json: @wheel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wheels/1
  # DELETE /wheels/1.json
  def destroy
    @wheel.destroy
    respond_to do |format|
      format.html { redirect_to wheels_url, notice: 'Wheel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wheel
      @wheel = Wheel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wheel_params
      params.require(:wheel).permit(:emotional_balance, :health_and_disposition, :intellectual_development, :career_and_business, :finances, :social_contribution, :recreation, :satisfaction_and_fullfillment, :spirituality, :family, :relationship_with_love, :social_life)
    end
end

app/helpers/wheels_helper.rb
module WheelsHelper
end

app/views/wheels/_form.html.erb
<%= form_for(@wheel) do |f| %>
  <% if @wheel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wheel.errors.count, "error") %> prohibited this wheel from being saved:</h2>

      <ul>
      <% @wheel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emotional_balance %><br>
    <%= f.number_field :emotional_balance %>
  </div>
  <div class="field">
    <%= f.label :health_and_disposition %><br>
    <%= f.number_field :health_and_disposition %>
  </div>
  <div class="field">
    <%= f.label :intellectual_development %><br>
    <%= f.number_field :intellectual_development %>
  </div>
  <div class="field">
    <%= f.label :career_and_business %><br>
    <%= f.number_field :career_and_business %>
  </div>
  <div class="field">
    <%= f.label :finances %><br>
    <%= f.number_field :finances %>
  </div>
  <div class="field">
    <%= f.label :social_contribution %><br>
    <%= f.number_field :social_contribution %>
  </div>
  <div class="field">
    <%= f.label :recreation %><br>
    <%= f.number_field :recreation %>
  </div>
  <div class="field">
    <%= f.label :satisfaction_and_fullfillment %><br>
    <%= f.number_field :satisfaction_and_fullfillment %>
  </div>
  <div class="field">
    <%= f.label :spirituality %><br>
    <%= f.number_field :spirituality %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.number_field :family %>
  </div>
  <div class="field">
    <%= f.label :relationship_with_love %><br>
    <%= f.number_field :relationship_with_love %>
  </div>
  <div class="field">
    <%= f.label :socialLife %><br>
    <%= f.number_field :socialLife %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wheels/edit.html.erb
<h1>Editing Wheel</h1>

<%= render 'form' %>

<%= link_to 'Show', @wheel %> |
<%= link_to 'Back', wheels_path %>

app/views/wheels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wheels</h1>

<table>
  <thead>
    <tr>
      <th>Emotional balance</th>
      <th>Health and disposition</th>
      <th>Intellectual development</th>
      <th>Career and business</th>
      <th>Finances</th>
      <th>Social contribution</th>
      <th>Recreation</th>
      <th>Satisfaction and fullfillment</th>
      <th>Spirituality</th>
      <th>Family</th>
      <th>Relationship with love</th>
      <th>Sociallife</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wheels.each do |wheel| %>
      <tr>
        <td><%= wheel.emotional_balance %></td>
        <td><%= wheel.health_and_disposition %></td>
        <td><%= wheel.intellectual_development %></td>
        <td><%= wheel.career_and_business %></td>
        <td><%= wheel.finances %></td>
        <td><%= wheel.social_contribution %></td>
        <td><%= wheel.recreation %></td>
        <td><%= wheel.satisfaction_and_fullfillment %></td>
        <td><%= wheel.spirituality %></td>
        <td><%= wheel.family %></td>
        <td><%= wheel.relationship_with_love %></td>
        <td><%= wheel.socialLife %></td>
        <td><%= link_to 'Show', wheel %></td>
        <td><%= link_to 'Edit', edit_wheel_path(wheel) %></td>
        <td><%= link_to 'Destroy', wheel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wheel', new_wheel_path %>

app/views/wheels/new.html.erb
<h1>New Wheel</h1>

<%= render 'form' %>

<%= link_to 'Back', wheels_path %>

app/views/wheels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emotional balance:</strong>
  <%= @wheel.emotional_balance %>
</p>

<p>
  <strong>Health and disposition:</strong>
  <%= @wheel.health_and_disposition %>
</p>

<p>
  <strong>Intellectual development:</strong>
  <%= @wheel.intellectual_development %>
</p>

<p>
  <strong>Career and business:</strong>
  <%= @wheel.career_and_business %>
</p>

<p>
  <strong>Finances:</strong>
  <%= @wheel.finances %>
</p>

<p>
  <strong>Social contribution:</strong>
  <%= @wheel.social_contribution %>
</p>

<p>
  <strong>Recreation:</strong>
  <%= @wheel.recreation %>
</p>

<p>
  <strong>Satisfaction and fullfillment:</strong>
  <%= @wheel.satisfaction_and_fullfillment %>
</p>

<p>
  <strong>Spirituality:</strong>
  <%= @wheel.spirituality %>
</p>

<p>
  <strong>Family:</strong>
  <%= @wheel.family %>
</p>

<p>
  <strong>Relationship with love:</strong>
  <%= @wheel.relationship_with_love %>
</p>

<p>
  <strong>Sociallife:</strong>
  <%= @wheel.socialLife %>
</p>

<%= link_to 'Edit', edit_wheel_path(@wheel) %> |
<%= link_to 'Back', wheels_path %>