config/routes.rb
Rails.application.routes.draw do

    # This line mounts Spree's routes at the root of your application.
    # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
    # If you would like to change where this engine is mounted, simply change the :at option to something different.
    #
    # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => 'users/registrations'}

    resources :temperaments
    resources :wheels
    resources :experiences
    resources :users, :except =>[:destroy]
    resources :tasks
    resources :goals
    resources :humors, :except =>[:destroy,:edit]
    resources :wheel_of_lives, :except =>[:destroy,:edit]
    resources :temperaments, :except =>[:destroy,:edit]
    resources :notifications

    root :to => "users#index"

    

    namespace :api do

        scope :users do
          post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
          post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
          delete '/sign_out_mobile',to:'/api/sessions#destroy'
          post '/reset_password',to:'/api/sessions#reset_password'
          post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
        end

        scope :goals do
            patch '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
        end

        get '/humors',to:'/api/humors#index', defaults: { format: 'json' }

        post '/create_humor',to:'/api/humors#create_humor', defaults: { format: 'json' }

        get '/goals',to:'/api/goals#index', defaults: { format: 'json' }

        post '/create_goal_image',to:'/api/goals#create_multipart_goal', defaults: { format: 'json' }

        get '/goals/:id',to:'/api/goals#show_goal', defaults: { format: 'json' }

        delete '/delete_goal/:id',to:'/api/goals#delete_goal', defaults: { format: 'json' }

        put '/finalize_goal/:id',to:'/api/goals#finalize_goal', defaults: { format: 'json' }

        get '/wheels',to:'/api/wheels#index', defaults: { format: 'json' }

        post '/new_wheel_of_life',to:'/api/wheels#create_wheel', defaults: { format: 'json' }

        get '/wheel_of_life',to:'/api/wheels#show_wheel', defaults: { format: 'json' }

        get '/temperaments',to:'/api/temperaments#index', defaults: { format: 'json' }

        post '/new_temperament',to:'/api/temperaments#create', defaults: { format: 'json' }

        get '/tasks',to:'/api/tasks#index', defaults: { format: 'json' }

        get '/tasks/:id',to:'/api/tasks#show_task', defaults: { format: 'json' }

        delete '/delete_task/:id',to:'/api/tasks#delete_task', defaults: { format: 'json' }

        put '/finalize_task/:id',to:'/api/tasks#finalize_task', defaults: { format: 'json' }

        get '/get_tasks/:goal_id',to:'/api/tasks#get_tasks', defaults: { format: 'json' }

        post '/create_task',to:'/api/tasks#create_task', defaults: { format: 'json' }

        get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

        post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' }

        get '/experiences',to:'/api/experiences#index', defaults: { format: 'json' }

        put '/update_mobile_multipart',to:'/api/registrations#update_multipart', defaults: { format: 'json' }

    end

end

app/models/experience.rb
class Experience < ActiveRecord::Base
	has_many :user
end

app/controllers/api/experiences_controller.rb
class Api::ExperiencesController < Api::BaseController

  respond_to :json

  def index
    @experiences = Experience.all
    render 'experiences/index.json.jbuilder'
  end
  
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:name)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.name %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @experience.name %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>