config/routes.rb
Rails.application.routes.draw do

    # This line mounts Spree's routes at the root of your application.
    # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
    # If you would like to change where this engine is mounted, simply change the :at option to something different.
    #
    # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => 'users/registrations'}

    resources :temperaments
    resources :wheels
    resources :experiences
    resources :users, :except =>[:destroy]
    resources :tasks
    resources :goals
    resources :humors, :except =>[:destroy,:edit]
    resources :wheel_of_lives, :except =>[:destroy,:edit]
    resources :temperaments, :except =>[:destroy,:edit]
    resources :notifications

    root :to => "users#index"

    

    namespace :api do

        scope :users do
          post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
          post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
          delete '/sign_out_mobile',to:'/api/sessions#destroy'
          post '/reset_password',to:'/api/sessions#reset_password'
          post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
          post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
        end

        scope :goals do
            patch '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
        end

        get '/humors',to:'/api/humors#index', defaults: { format: 'json' }

        post '/create_humor',to:'/api/humors#create_humor', defaults: { format: 'json' }

        get '/goals',to:'/api/goals#index', defaults: { format: 'json' }

        post '/create_goal_image',to:'/api/goals#create_multipart_goal', defaults: { format: 'json' }

        get '/goals/:id',to:'/api/goals#show_goal', defaults: { format: 'json' }

        delete '/delete_goal/:id',to:'/api/goals#delete_goal', defaults: { format: 'json' }

        put '/finalize_goal/:id',to:'/api/goals#finalize_goal', defaults: { format: 'json' }

        get '/wheels',to:'/api/wheels#index', defaults: { format: 'json' }

        post '/new_wheel_of_life',to:'/api/wheels#create_wheel', defaults: { format: 'json' }

        get '/wheel_of_life',to:'/api/wheels#show_wheel', defaults: { format: 'json' }

        get '/temperaments',to:'/api/temperaments#index', defaults: { format: 'json' }

        post '/new_temperament',to:'/api/temperaments#create', defaults: { format: 'json' }

        get '/tasks',to:'/api/tasks#index', defaults: { format: 'json' }

        get '/tasks/:id',to:'/api/tasks#show_task', defaults: { format: 'json' }

        delete '/delete_task/:id',to:'/api/tasks#delete_task', defaults: { format: 'json' }

        put '/finalize_task/:id',to:'/api/tasks#finalize_task', defaults: { format: 'json' }

        get '/get_tasks/:goal_id',to:'/api/tasks#get_tasks', defaults: { format: 'json' }

        post '/create_task',to:'/api/tasks#create_task', defaults: { format: 'json' }

        get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

        post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' }

        get '/experiences',to:'/api/experiences#index', defaults: { format: 'json' }

        put '/update_mobile_multipart',to:'/api/registrations#update_multipart', defaults: { format: 'json' }

    end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
    belongs_to :user
    has_many :tasks

    has_attached_file :image, default_url: "images/target_estiloso.png",styles: { medium: "300x300>", thumb: "100x100>"}
    validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

    # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/casa.jpg"
    # validates_attachment :image, content_type: { content_type: ["image/jpg", "image/gif", "image/png"] }

    def self.calculate_status
        values = Array.new
        finalized = Array.new
        percentage = 0

        for task in tasks do

            if task.goal_id != nil 
                values.push(task.goal_id)
            end	

            if task.status == "Finalizada"
                finalized.push(task.goal_id)
            end	

        end

        if values.size != 0 and finalized.size != 0
            percentage = finalized.size.to_f/values.size.to_f * 100
            return percentage.to_int
        else
            return percentage
        end 

    end

end

app/controllers/api/goals_controller.rb
class Api::GoalsController < Api::BaseController

	before_filter :authenticate_user!
    respond_to :json
  
	def index
		@goals = current_user.goals
		render 'goals/index.json.jbuilder'
	end

	def show_goal
		@goal = Goal.find(params[:id])
		render 'goals/show.json.jbuilder' 
	end

	    # POST /resource
	def create_multipart_goal
	    
	    if params['goal']['date_realization'] >= DateTime.now
	    	@goal = Goal.new
		    @goal.user = current_user
		    @goal.description = params['goal']['description']
			@goal.status = "Em Andamento"
			@goal.image = params['goal']['image']
			@goal.date_realization = params['goal']['date_realization']
			@goal.specific = params['goal']['specific']
			@goal.temporal = params['goal']['temporal']
			@goal.relevant = params['goal']['relevant']
			@goal.reachable = params['goal']['reachable']
			@goal.measurable = params['goal']['measurable']
			@goal.ecological = params['goal']['ecological']
			@goal.save

			if @goal.persisted?
				render 'goals/show.json.jbuilder' 
			    return @goal
			else
				logger.info @goal.errors.full_messages
			end

		else
			render json: { error: "Data inferior a data atual.", status: 400 } , status: :bad_request
		end
	end

	def delete_goal
        @goal = Goal.find(params[:id])
        @goal.destroy
        render json: {success: true}
    end

    def finalize_goal
        @goal = Goal.find(params[:id])
        @goal.status = "Finalizada"
        @goal.save
        render json: {success: true}
    end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:image, :date_realization,:description,:status, :calculate_status,{:tasks => []},:specific,:temporal,:relevant,:reachable,:measurable,:ecological)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal, url: goals_path, html: { multipart: true } do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :date_realization %><br>
    <%= f.date_field :date_realization %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Goals</h1>

<table>
  <thead>
    <tr>
      <th>Imagem</th>
      <th>Description</th>
      <th>Date realization</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= image_tag goal.image.url(:thumb) %></td>
        <td><%= goal.description %></td>
        <td><%= goal.date_realization %></td>
        <td><%= goal.status %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <td><%= image_tag @goal.image.url(:medium) %></td>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Date realization:</strong>
  <%= @goal.date_realization %>
</p>

<p>
  <strong>Status:</strong>
  <%= @goal.status %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

</br>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Date realization</th>
      <th>Status</th>
      <th>Type frquency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goal.tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.date_realization %></td>
        <td><%= task.status %></td>
        <td><%= task.type_frequency %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_task_path %>